### ISSUE TITLE
Billing plan > Avoid counting string twice

### ISSUE THREAD

**Issue by MiladSadinam** [WeblateOrg/hosted#41]
Hello,

we are using weblate hosted on https://hosted.weblate.org/. We want to translate a bilingual xliff file using git as Version Control System. Unfortunately weblate always creates two languages for the component: The source language and the target language. Meaning that our source string numbers are counted twice concerning the billing plan. Is there a way to avoid this?

We currently have exceeded the number strings available by our billing plan. Does the account now have any limitations?

Regards
Milad

**Comment by nijel** [comment]
The billing should count only source strings, it doesn't matter how many translations are there. If I'm guessing your project correctly, you currently have three components:

* Backend - 802 strings
* Backend-test - 758 strings
* Frontend - 2,574 strings

That makes in total 4134, what is more than 3000 allowed in the medium plan.

PS: Usually it's better to reach us at support@weblate.org with such queries so that we do not discuss potentially private information in the public issue tracker.

**Comment by MiladSadinam** [comment]
Yes you guesses the project correctly. Thanks you for your clarification. If I should have more questions I will contact you at the e-mail address.
